[phases.setup]
nixPkgs = ["python311"]

[phases.build]
cmds = [
  "python3 -m ensurepip --upgrade",
  "pip install --upgrade pip",
  "pip install -r requirements-lite.txt"
]

[phases.start]
cmd = "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
