[phases.setup]
nixPkgs = ["python311"]

[phases.build]
cmds = [
  "pip3 install -r requirements-lite.txt"
]

[phases.start]
cmd = "python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
