[phases.setup]
nixPkgs = ["python311Full", "pipx"]

[phases.build]
cmds = [
  "pipx run pip install --upgrade pip",
  "pipx run pip install -r requirements-lite.txt"
]

[phases.start]
cmd = "python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
