# Generated by Django 4.2.7 on 2024-12-15 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_category_record'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='id',
            new_name='member',
        ),
    ]
